#!/bin/bash

set -eu

install_juju() {
  apt-add-repository ppa:juju/pkgs
  apt-get update
  apt-get -qq install -y juju charm-tools apt-cacher-ng zookeeper libvirt-bin lxc charm-helper-sh
}
install_juju

configure_juju_local_provider() {
  mkdir -p /home/ubuntu/.juju
  cat > /home/ubuntu/.juju/environments.yaml <<EOF
environments:
  local:
    type: local
    data-dir: /tmp/juju-local
    admin-secret: abcdefghijklmnopqrstuvwxyz1234567890
    control-bucket: foo-bucket
    default-series: oneiric
EOF
  chown -Rf ubuntu.ubuntu /home/ubuntu/.juju
}
configure_juju_local_provider

generate_ssh_keys() {
  su -l ubuntu -c "ssh-keygen -q -N '' -t rsa -b 2048 -f /home/ubuntu/.ssh/id_rsa"
}
[ -f /home/ubuntu/.ssh/id_rsa ] || generate_ssh_keys

enable_ssh_passwords() {
  sed -i 's/PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
  service ssh restart
}
enable_ssh_passwords


